# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
    
  # Image configuration (for all vm's)
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202309.08.0"
  
  # SSH (for all vm's)
  config.ssh.insert_key = false
  config.ssh.forward_agent = true  
  config.ssh.private_key_path = ["/home/aagustin/.vagrant.d/insecure_private_key","/home/aagustin/.ssh/vagrant_key"]     
  config.vm.provision "file", source: "/home/aagustin/.ssh/vagrant_key.pub", destination: "/home/vagrant/.ssh/authorized_keys"

  # How many VMs to create 
  VMS = 3
  
# We need at least:
  # -initial_controller = must contain a single node that creates the worker and server tokens needed by the other nodes.
  # -controller = can contain nodes that, together with the host from initial_controller form a highly available isolated control plane.
  # -worker = must contain at least one node so that we can deploy Kubernetes objects.
  

  # Declaring nodes (iteratively)
  (1..VMS).each do |i|
    config.vm.define "k0s-#{i}" do |node|
      
      # Resources (provider)
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.name = "trusty64-k0s-#{i}"
        vb.memory = "1024"
        vb.cpus = "2"
      end

      # Configure synced folder
      #config.vm.synced_folder "~/my-loc/vagrant/synced/folders/k0s-#{i}/", "/home/vagrant/"

      # Network configuration
      node.vm.network "public_network",
        bridge:"wlo1",
        ip: "192.168.102.20#{1+i}",
        netmask: "255.255.255.0"
      
      node.vm.network "private_network",
        ip: "192.168.55.#{1+i}",
        netmask: "255.255.255.0",
        virtualbox__intnet: true
        #auto_config: false
      
      node.vm.network "forwarded_port",
        guest: 80,
        host: 31001+i

      # SSH
      node.ssh.host = "127.0.0.#{1+i}"
      node.ssh.forward_agent = true
      node.vm.network "forwarded_port",
        guest: 22,
        host: 2221+i,
        host_ip:"0.0.0.0",
        id: "ssh",
        auto_correct: true
           
      # Provisioning message
      node.vm.provision "shell", inline: "echo Hello node-#{i}"
    end      
  
  end

end

